-- FASTBITE POS ORACLE DATABASE
-- Run this while connected to the schema/user where you want the tables.

BEGIN EXECUTE IMMEDIATE 'DROP TABLE order_items CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE orders CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE products CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE categories CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE categories (
    category_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name VARCHAR2(50) NOT NULL UNIQUE
);

CREATE TABLE products (
    product_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name VARCHAR2(100) NOT NULL,
    category_id NUMBER NOT NULL,
    price NUMBER(10,2) NOT NULL CHECK (price >= 0),
    stock_qty NUMBER DEFAULT 0 NOT NULL CHECK (stock_qty >= 0),
    is_available CHAR(1) DEFAULT 'Y' NOT NULL CHECK (is_available IN ('Y','N')),
    CONSTRAINT fk_product_category
        FOREIGN KEY (category_id) REFERENCES categories(category_id)
);

CREATE TABLE orders (
    order_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number VARCHAR2(30) NOT NULL UNIQUE,
    order_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    subtotal NUMBER(10,2) NOT NULL,
    tax_amount NUMBER(10,2) NOT NULL,
    total_amount NUMBER(10,2) NOT NULL,
    payment_method VARCHAR2(20) NOT NULL,
    cash_received NUMBER(10,2),
    change_amount NUMBER(10,2),
    status VARCHAR2(20) DEFAULT 'COMPLETED' NOT NULL
);

CREATE TABLE order_items (
    order_item_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id NUMBER NOT NULL,
    product_id NUMBER NOT NULL,
    quantity NUMBER NOT NULL CHECK (quantity > 0),
    unit_price NUMBER(10,2) NOT NULL,
    subtotal NUMBER(10,2) NOT NULL,
    CONSTRAINT fk_item_order
        FOREIGN KEY (order_id) REFERENCES orders(order_id) ON DELETE CASCADE,
    CONSTRAINT fk_item_product
        FOREIGN KEY (product_id) REFERENCES products(product_id)
);

INSERT INTO categories (category_name) VALUES ('Burgers');
INSERT INTO categories (category_name) VALUES ('Chicken');
INSERT INTO categories (category_name) VALUES ('Sides');
INSERT INTO categories (category_name) VALUES ('Drinks');
INSERT INTO categories (category_name) VALUES ('Desserts');

INSERT INTO products (product_name, category_id, price, stock_qty)
SELECT 'Classic Burger', category_id, 99, 50 FROM categories WHERE category_name = 'Burgers';
INSERT INTO products (product_name, category_id, price, stock_qty)
SELECT 'Cheese Burger', category_id, 119, 50 FROM categories WHERE category_name = 'Burgers';
INSERT INTO products (product_name, category_id, price, stock_qty)
SELECT 'Crispy Chicken', category_id, 139, 40 FROM categories WHERE category_name = 'Chicken';
INSERT INTO products (product_name, category_id, price, stock_qty)
SELECT 'Chicken Nuggets 6pc', category_id, 129, 40 FROM categories WHERE category_name = 'Chicken';
INSERT INTO products (product_name, category_id, price, stock_qty)
SELECT 'Regular Fries', category_id, 59, 80 FROM categories WHERE category_name = 'Sides';
INSERT INTO products (product_name, category_id, price, stock_qty)
SELECT 'Large Fries', category_id, 79, 60 FROM categories WHERE category_name = 'Sides';
INSERT INTO products (product_name, category_id, price, stock_qty)
SELECT 'Cola', category_id, 49, 100 FROM categories WHERE category_name = 'Drinks';
INSERT INTO products (product_name, category_id, price, stock_qty)
SELECT 'Iced Tea', category_id, 55, 100 FROM categories WHERE category_name = 'Drinks';
INSERT INTO products (product_name, category_id, price, stock_qty)
SELECT 'Sundae', category_id, 69, 50 FROM categories WHERE category_name = 'Desserts';
